### ISSUE TITLE
Video layout needs improvement

### ISSUE THREAD

**Issue by jgzamora** [SparkPost/sparkpost.github.io#52]
The current Videos layout doesn't look very helpful. Would suggest having whatever is considered the main intro video featured at the top and a list of categories or video titles for the rest. Maybe even a numbered list of what to go through first + categories next to it to get to specific topics? At the very least, the video titles should be more noticeable than the video description. @aydrian suggested something like  https://egghead.io/

**Comment by richleland** [comment]
Videos section was removed with #118.
