### ISSUE TITLE
Create SparkPost Lab page

### ISSUE THREAD

**Issue by aydrian** [SparkPost/sparkpost.github.io#60]
Users should be able to access SparkPost Lab at `/lab`. I'm not sure if it should be plural or not.
Page should include:
- [ ] SparkPost Account Signup Link w/ salesforce campaign info
- [ ] 3 Mini Hacks with descriptions

**Comment by richleland** [comment]
definitely not plural

**Comment by aydrian** [comment]
Great. Updated the title and description.
