### ISSUE TITLE
Create code snippets for home page

### ISSUE THREAD

**Issue by richleland** [SparkPost/sparkpost.github.io#9]
Let's create some code snippets for display under the hero:
- [x] cURL
- [x] JavaScript
- [x] Python
- [x] Node.js

**Comment by cristoirmac** [comment]
this came in from twitter https://twitter.com/orliesaurus/status/711731457601843200
there is a problem with the CURL example.  "add a space between the -X & POST also drop the ";" at the end of your API key its confusing."
